### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by Juank628**
## To-do-list: initial setup
In this pull request, I did the following:
- Created a React project using CRA
- Deleted all unnecessary boilerplate from CRA
- Created all the components required for Todo list functionalities
- Created routes using the React-router library

### CODE REVIEW

**Comment by sambeck87** [comment]
so_close
 ## Changes required
 - Kindly suggest you use the Microverse template README file and fill it with your project information.
 
### Highlights:
 - Good descriptive title :heavy_check_mark: 
 - Good commits  :heavy_check_mark: 
 - Good Gitflow use  :heavy_check_mark: 
 - App works well  :heavy_check_mark: 
 - All linters passing :heavy_check_mark:

**Comment by sambeck87** [comment]
so_close
 ## Changes required
 - Kindly suggest you use the Microverse template README file and fill it with your project information.
 
### Highlights:
 - Good descriptive title :heavy_check_mark: 
 - Good commits  :heavy_check_mark: 
 - Good Gitflow use  :heavy_check_mark: 
 - App works well  :heavy_check_mark: 
 - All linters passing :heavy_check_mark: 

## Optional:
I suggest you match the name of your project with its functionality. This way you will avoid confusion when someone tries to use it. :sunglasses:

**Comment by Juank628** [comment]
> so_close [ so_close ](https://user-images.githubusercontent.com/113067895/212944310-92d44f25-d2ef-436e-8979-5a7999475675.gif) [ ](https://user-images.githubusercontent.com/113067895/212944310-92d44f25-d2ef-436e-8979-5a7999475675.gif)
> 
> ## Changes required
> * Kindly suggest you use the Microverse template README file and fill it with your project information.
> 
> ### Highlights:
> * Good descriptive title ✔️
> * Good commits  ✔️
> * Good Gitflow use  ✔️
> * App works well  ✔️
> * All linters passing ✔️
> 
> ## Optional:
> I suggest you match the name of your project with its functionality. This way you will avoid confusion when someone tries to use it. 😎

Thanks for your comments!!!

**Comment by sambeck87** [comment]
you_did_it
### Nothing more to say. Your project is finished

## Highlights
- Good descriptive title :heavy_check_mark: 
- Good commits  :heavy_check_mark: 
- Good Gitflow use  :heavy_check_mark: 
- App works well  :heavy_check_mark: 
- All linters passing  :heavy_check_mark: 
- Professional Readme description  :heavy_check_mark:

**Pull request merged**
